name: dev

on:
  push:
    branches: ['**']
    paths-ignore:
      - '**/*.md'
      - '.github/**'

env: 
  JAVA_VERSION: '21'

jobs:
  dev:
    runs-on: ubuntu-latest
    concurrency: 
      group: release
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ env.JAVA_VERSION }}
        cache: gradle

    - run: ./gradlew assembleDebug --stacktrace

    - name: Read version from Gradle
      run: |
        VERSION_NAME=$(./gradlew -q printVersionName)
        VERSION_CODE=$(./gradlew -q printVersionCode)
        echo "VERSION_NAME=$VERSION_NAME" >> "$GITHUB_ENV"
        echo "VERSION_CODE=$VERSION_CODE" >> "$GITHUB_ENV"

    - name: Rename APK
      run: |
        APK_OUT=$(ls app/build/outputs/apk/debug/app-debug.apk)
        mv "$APK_OUT" "app/build/outputs/apk/debug/DroidPlane-${VERSION_NAME}-dev.apk"

    - uses: actions/upload-artifact@v4
      with:
        name: DroidPlane-${{ env.VERSION_NAME }}-dev
        path: app/build/outputs/apk/debug/DroidPlane-${{ env.VERSION_NAME }}-dev.apk

